### PR TITLE
[FormsyCheckbox] Fix error on form reset

### LINKED ISSUE #74: FormsyCheckbox error on form reset
I have a form which contains some FormsyCheck: 

```
<Formsy.Form
          ref='searchForm'
          method="GET"
          className="form"
          onValidSubmit={this.submitForm}
          onInvalidSubmit={this.submitForm}
          onChange={onChange}
 >
        <FormsyCheckbox
            name={name}
            floatingLabelText={name}
            label={name}
            defaultChecked={!!defaultValue}
        />
 
        <RaisedButton
            label="Reset"
            onTouchTap={onReset}
         />.
```

when Inside **onReset** I  call 

`this.refs.searchForm.reset();`

I have the following warning:

`warning.js:45 Warning: Failed propType: Required prop `switched` was not specified in `EnhancedSwitch`. Check the render method of `Checkbox`.`

### PR DESCRIPTION
**Pull request by jurgob**
Closes #74

### CODE REVIEW

File: src/FormsyCheckbox.jsx [hunk 1]
```diff
@@ -22,12 +22,17 @@ let FormsyCheckbox = React.createClass({
   _setMuiComponentAndMaybeFocus: _setMuiComponentAndMaybeFocus,
 
   render: function () {
+    var _value = this.getValue();
+    var defaultChecked = this.props.defaultChecked;
+    if(typeof _value  === 'undefined' )
```
Comment (mbrookes) [inline src/FormsyCheckbox.jsx]: Please remove the extra space and put in braces for this, and remove the underscore dangle.

Thanks.

**Comment by mbrookes** [comment]
Hi @jurgob - if you could make those changes and squash, I'll merge this.

**Comment by jurgob** [comment]
I did what you had requested @mbrookes
