### PR TITLE
[FormsySelect] Fix Unknown prop `requiredError` error / misc refactoring

### LINKED ISSUE #204: requiredError on FormsySelect
When I try to add the `requiredError` prop on a `FormsySelect`, I get this error:

```
Warning: Unknown prop `requiredError` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by TextField)
    in TextField (created by SelectField)
    in SelectField (created by FormsySelect)
    in FormsySelect (at ProductFormPage.js:82)
```

I think the problem is that the `requiredError` prop is not declared here: https://github.com/mbrookes/formsy-material-ui/blob/master/src/FormsySelect.jsx#L45, thus it is in `{...rest}`, which is then passed down to `SelectField` etc.

### PR DESCRIPTION
**Pull request by mbrookes**
Closes #204

### CODE REVIEW

File: src/FormsySelect.jsx [hunk 1]
```diff
@@ -37,18 +37,20 @@ const FormsySelect = React.createClass({
...
-        validationError, // eslint-disable-line no-unused-vars
-        validationErrors, // eslint-disable-line no-unused-vars
-      ...rest } = this.props;
-
-    value = this.state.hasChanged ? this.getValue() : value;
-    const { requiredError } = this.props;
     const { isRequired, isPristine, isValid, isFormSubmitted } = this;
     const isRequiredError = isRequired() && !isPristine() && !isValid() && isFormSubmitted() && requiredError;
     const errorText = this.getErrorMessage() || isRequiredError;
+    value = this.state.hasChanged ? this.getValue() : valueProp;
```
Comment (ulich) [inline src/FormsySelect.jsx]: I am getting `ReferenceError: value is not defined`

You are missing the variable declaration

Comment (mbrookes) [inline src/FormsySelect.jsx]: Yeah, sorry. That's what I get for trying to fix on the flay! 😄 

Try now.

**Comment by ulich** [comment]
works 👍
